language: ruby
rvm:
  - "2.1.5"
script:
  - RAILS_ENV=test bundle exec rake db:migrate spec
before_script:
  - psql -c 'create database contribulator_test' -U postgres
sudo: false
cache: bundler
env:
  - DB=postgresql
