language: ruby
rvm:
  - "2.3.3"
script:
  - RAILS_ENV=test bundle exec rake db:migrate spec && bundle exec codeclimate-test-reporter
before_install:
  - gem update --system
before_script:
  - psql -c 'create database contribulator_test' -U postgres
sudo: false
cache: bundler
env:
  - DB=postgresql
