name: CI

on: [push]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: contribulator
          POSTGRES_DB: contribulator_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          POSTGRES_DB: contribulator_test
          POSTGRES_USER: contribulator
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: bundle exec rake db:create db:migrate spec
